name = "tornapi-plugin-gpt"
main = "worker.js"
compatibility_date = "2026-09-27"
compatibility_flags = ["global_fetch_strictly_public"]
workers_dev = true

[vars]
TORN_OPENAPI_URL = "https://www.torn.com/swagger/openapi.json"
TORN_API_BASE = "https://api.torn.com/v2"
TORN_USER_AGENT = "TornChatGPT/1.0"

[[kv_namespaces]]
binding = "OAUTH_KV"
id = "406d695c89204c67b75fc71a065ba113"
